# Generated by Django 4.0 on 2022-06-29 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_profile_photo_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.IntegerField()),
                ('date', models.DateField()),
                ('reference_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('refund', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project_Deatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_detail', models.CharField(max_length=100)),
                ('booking_amount', models.IntegerField()),
                ('total_project_value', models.IntegerField()),
                ('project_booking_date', models.DateTimeField()),
                ('paid_amount', models.IntegerField()),
                ('remaining_amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Project_Details',
        ),
        migrations.AddField(
            model_name='project_deatails',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='users.profile'),
        ),
        migrations.AddField(
            model_name='payment_tracking',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_tracking', to='users.profile'),
        ),
        migrations.AddField(
            model_name='payment_tracking',
            name='project_deatails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.project_deatails'),
        ),
    ]
