# Generated by Django 4.0 on 2022-06-29 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_payment_tracking_project_deatails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_tracking',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='project_deatails',
            name='profile',
        ),
        migrations.AddField(
            model_name='payment_tracking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_tracking', to='auth.user'),
        ),
        migrations.AddField(
            model_name='project_deatails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_details', to='auth.user'),
        ),
    ]
